version: '3.7'
services:
  api:
    container_name: api
    image: api-myspend:latest
    restart: on-failure
    networks:
      - myspend_network
    depends_on:
      - postgres
    ports:
      - 8000:8000
  postgres:
    container_name: postgres_myspend
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${password}
    expose:
      - 5432
    ports:
      - 6000:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - myspend_network
  storage:
    container_name: minio
    image: minio/minio:latest
    volumes:
      - storage_volume:/data
    networks:
      - myspend_network
    ports:
      - 9000:9000
      - 9001:9001
    expose:
      - 9000
      - 9001
    environment:
      - MINIO_ROOT_USER=${minio_user}
      - MINIO_ROOT_PASSWORD=${minio_password}
    command: server --console-address ":9001" /data
volumes:
  postgres_volume:
  storage_volume:

networks:
  myspend_network:
