version: '3.7'
services:
  api:
    container_name: api
    image: api-myspend:latest
    restart: on-failure
    networks:
      - myspend_network
    depends_on:
      - postgres
    ports:
      - 8000:8000
  postgres:
    container_name: postgres_myspend
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${password}
    expose:
      - 5432
    ports:
      - 6000:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - myspend_network
volumes:
  postgres_volume:

networks:
  myspend_network:
